version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - E:\CSDF project\Web_forensic\mount
    environment:
      - FLASK_ENV=development
    command: python app.py # Ensure the start.sh script is run when the container starts
